name: Python Package CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8 mypy pytest

    - name: Run tests
      run: pytest

    - name: Run Black
      run: black --check .

    - name: Run Flake8
      run: flake8 .

    - name: Type Checking with MyPy
      run: mypy OptunaFS/
