name: Python Package CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools
          pip install numpy pandas scikit-learn optuna pytest black flake8 mypy
          pip install -e .
          
      - name: Check for tests
        id: check_tests
        run: |
          if [ -z "$(find tests -name 'test_*.py')" ]; then
            echo "No tests found."
            echo "skip_tests=true" >> $GITHUB_ENV
          else
            echo "Tests found."
            echo "skip_tests=false" >> $GITHUB_ENV
          fi
          
      - name: Run tests
        if: env.skip_tests == 'false'
        run: pytest tests/
        
      - name: Run Black
        run: black --check .
        
      - name: Run Flake8
        run: flake8 .
        
      - name: Type Checking with MyPy
        run: mypy .