name: Python Package CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8==7.0.0 mypy==1.8.0 pytest
        pip install types-setuptools types-six
        pip install 'pandas-stubs==2.2.2.240807'
        pip install types-PyYAML
        pip install -e .
    - name: Format
      run: black .
    - name: Test
      if: env.skip_tests == 'false'
      run: pytest